### ISSUE TITLE
building on Ubuntu 20.04 : libraries problems

### ISSUE THREAD

**Issue by ddavout** [johnfactotum/foliate#665]
Following the README
I first have the warning 

> Could not detect glib version, assuming 2.54. You may get build errors if your glib is older.

despite the fact my version of glib was and is 2.64 ; in the README is omitted the fact we need as well libglib2.0-dev 

Then, the next step failed silently .. after the messages
 > Running custom install script '/home/yop/Downloads/foliate-2.5.0/build-aux/meson/postinstall.py'
>  Updating icon cache...
> Updating desktop database...
> Compiling GSettings schemas...
I've tried to run manually the python3 script, I've got more information about the failure

> Error opening directory “/usr/local/share/glib-2.0/schemas”: No such file or director
I edited the script, and change datadir 
`datadir = "/usr/share"
#datadir = path.join(prefix, 'share')`
to solve my issue

in the README, a typo
`libhandy` (`gir1.2-tracker-2.0`) is recommended to make the interface work
the debian name for libhandy is libhandy-0.0,; I presume that the dev is needed but I did not need this optional package

Thanks for your work, and for the result of it :)

**Comment by johnfactotum** [comment]
> Could not detect glib version, assuming 2.54. You may get build errors if your glib is older.

That's just a warning, as far as know. It shouldn't cause any errors.

>Then, the next step failed silently .. after the messages

What commands did you run? And how exactly does it fail?

>  I've tried to run manually the python3 script, I've got more information about the failure
> Error opening directory “/usr/local/share/glib-2.0/schemas”: No such file or director

When you're running it manually, `MESON_INSTALL_PREFIX` is not set, and it will default to `/usr/local`, which is why you're seeing that error. If you want it to use `/usr/share` instead of `/usr/local/share`, then you must set the prefix to `/usr`.

> in the README, a typo libhandy (gir1.2-tracker-2.0) is recommended to make the interface work

This is already fixed on master with 0b4d37d022c3046a28494d827eca4a750d19c3a9.

**Comment by ddavout** [comment]
Sorry I was certainly not clear when I build and when I report the problems I encountered :(
at my first trial, the failure was far from silencious
I then understood that one requisite were not explicit
I needed as well the libglib2.0-dev
and sorry to have wasted your time ..
I have may be overlooked the stanza about GSETTINGS_SCHEMA_DIR
or paste two commands at the same time ...
I appreciate you have even taken time to give me some explanations about PREFIX
and I thanks you to allow to enjoy the fruits of your work, nice piece of work this foliate

Source dir: /home/yop/Downloads/debug/foliate-2.5.0
Build dir: /home/yop/Downloads/debug/foliate-2.5.0/build
Build type: native build
Project name: com.github.johnfactotum.Foliate
Project version: 2.5.0
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program desktop-file-validate found: YES (/usr/bin/desktop-file-validate)
Program appstream-util found: NO
Program glib-compile-schemas found: YES (/usr/bin/glib-compile-schemas)
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Run-time dependency iso-codes found: YES 4.4
Configuring isoCodes.js using configuration
Found pkg-config: /usr/bin/pkg-config (0.29.1)
WARNING: Could not detect glib version, assuming 2.54. You may get build errors if your glib is older.
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/mesonbuild/mesonmain.py", line 129, in run
return options.run_func(options)
File "/usr/lib/python3/dist-packages/mesonbuild/msetup.py", line 245, in run
app.generate()
File "/usr/lib/python3/dist-packages/mesonbuild/msetup.py", line 159, in generate
self._generate(env)
File "/usr/lib/python3/dist-packages/mesonbuild/msetup.py", line 192, in _generate
intr.run()
File "/usr/lib/python3/dist-packages/mesonbuild/interpreter.py", line 4167, in run
super().run()
File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase.py", line 412, in run
self.evaluate_codeblock(self.ast, start=1)
File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase.py", line 436, in evaluate_codeblock
raise e
File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase.py", line 430, in evaluate_codeblock
self.evaluate_statement(cur)
File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase.py", line 441, in evaluate_statement
return self.function_call(cur)
File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase.py", line 788, in function_call
return func(node, posargs, kwargs)
File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase.py", line 285, in wrapped
return f(*wrapped_args, **wrapped_kwargs)
File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase.py", line 174, in wrapped
return f(*wrapped_args, **wrapped_kwargs)
File "/usr/lib/python3/dist-packages/mesonbuild/interpreter.py", line 3689, in func_subdir
self.evaluate_codeblock(codeblock)
File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase.py", line 436, in evaluate_codeblock
raise e
File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase.py", line 430, in evaluate_codeblock
self.evaluate_statement(cur)
File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase.py", line 443, in evaluate_statement
return self.assignment(cur)
File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase.py", line 1064, in assignment
value = self.evaluate_statement(node.value)
File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase.py", line 445, in evaluate_statement
return self.method_call(cur)
File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase.py", line 828, in method_call
return obj.method_call(method_name, args, kwargs)
File "/usr/lib/python3/dist-packages/mesonbuild/interpreter.py", line 1756, in method_call
value = fn(state, args, kwargs)
File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase.py", line 285, in wrapped
return f(*wrapped_args, **wrapped_kwargs)
File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase.py", line 174, in wrapped
return f(*wrapped_args, **wrapped_kwargs)
File "/usr/lib/python3/dist-packages/mesonbuild/modules/gnome.py", line 145, in compile_resources
depend_files, depends, subdirs = self._get_gresource_dependencies(
File "/usr/lib/python3/dist-packages/mesonbuild/modules/gnome.py", line 229, in _get_gresource_dependencies
pc, stdout, stderr = Popen_safe(cmd, cwd=state.environment.get_source_dir())
File "/usr/lib/python3/dist-packages/mesonbuild/mesonlib.py", line 1089, in Popen_safe
p = subprocess.Popen(args, universal_newlines=True, close_fds=False,
File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
self._execute_child(args, executable, preexec_fn, close_fds,
File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'glib-compile-resources'
yop@yop-Latitude-E6430:~/Downloads/debug/foliate-2.5.0$

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by itprojects** [comment]
@ddavout There was an error at the end, that may require some attention:

> FileNotFoundError: [Errno 2] No such file or directory: 'glib-compile-resources'

`glib-compile-resources` comes from `libglib2.0-dev-bin`

**Comment by itprojects** [comment]
@ddavout Is this still an issue? Foliate successfully compiles from source in Ubuntu 20.04.2 LTS using the given the Readme.md instructions. Could it be that your machine has somehow different libraries or packages than those that should be installed?

**Comment by ddavout** [comment]
Sorry, I was not clear enough, I thought I told you that I was already enjoying your lovely software. Thanks

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by itprojects** [comment]
Great. We can close this bug.
